### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by Secret-chest** [openrecycle/dataset#3]
I'm looking to use this dataset in my project. Is it available with a free (allows any use, even commercial, derivatives and all kinds of redistribution) licence?

**Comment by todatasudata** [comment]
It's free, hope it will help you in your work

**Comment by Secret-chest** [comment]
Thanks for replying.
What kind of free?
I'm looking to make a model myself, combining this with other datasets. I also need:
* to be able to distribute my model and the data on a github
* to be able to modify this data
* even commercially

I would give credit.

Would you choose a licence to make it clearer? Right now, without a licence, this is all rights reserved.

**Comment by todatasudata** [comment]
Sorry for waiting.
The problem is that pictures are just scraped from google search long time ago (so we even can't give exact sources for them). So definitely we can't provide any license for it and probably gonna close repo due to legal issues.

**Comment by todatasudata** [comment]
Didn't expect so serious conversation, thank you for your questions:)

**Comment by Secret-chest** [comment]
That's fine, I won't use it then. Better safe than sorry.
